# Generated by Django 4.1 on 2022-08-22 02:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(error_messages={'unique': '入力されたメールアドレスは既に登録済みです。'}, max_length=254, unique=True, verbose_name='メールアドレス')),
                ('memo', models.TextField(blank=True, max_length=200, verbose_name='メモ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
            ],
        ),
        migrations.CreateModel(
            name='MailTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='名前')),
                ('description', models.CharField(max_length=512, verbose_name='説明')),
            ],
        ),
        migrations.CreateModel(
            name='SystemMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='名前')),
                ('subject', models.CharField(blank=True, max_length=64, verbose_name='件名')),
                ('content', models.CharField(blank=True, max_length=2000, verbose_name='本文')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mail.mailaddress')),
            ],
        ),
    ]
