name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Py ${{ matrix.python }} / Django ${{ matrix.django }}
    env:
      DJANGO_SETTINGS_MODULE: core.dev
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python: [3.8, 3.9]
        django: [4.1]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python: ${{ matrix.python }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade Django==${{ matrix.django }}
    - name: Run Tests
      run: |
        python manage.py test -v2
